version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: im-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: im-system
    networks:
      - im-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: im-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/im-system
      - JWT_SECRET=your-secret-key-change-in-production-2024
    depends_on:
      - mongodb
    networks:
      - im-network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: im-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - im-network

networks:
  im-network:
    driver: bridge

volumes:
  mongodb_data:

