name: Build and Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node and Docker
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker-compose

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASS: ${{ secrets.SERVER_PASS }}
        run: |
          echo "Connecting to $SERVER_HOST ..."
          sudo apt-get install -y sshpass
          sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
            cd /www/wwwroot/imlast || mkdir -p /www/wwwroot/imlast && cd /www/wwwroot/imlast;
            git pull || git clone https://github.com/Gymmmm/imlast.git .;
            docker-compose down;
            docker-compose up -d --build;
            docker ps
          "