name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Run tests
      run: |
        cd backend
        npm test || echo "No tests configured"

    - name: Check code quality
      run: |
        cd backend
        npm run lint || echo "No lint script"
        npx tsc --noEmit || echo "No TypeScript config"

  frontend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend_production/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend_production
        npm ci

    - name: Run tests
      run: |
        cd frontend_production
        npm test || echo "No tests configured"

    - name: Build project
      run: |
        cd frontend_production
        npm run build
      env:
        VITE_API_URL: http://localhost:3001
        VITE_SOCKET_URL: http://localhost:3001

    - name: Check code quality
      run: |
        cd frontend_production
        npm run lint || echo "No lint script"
        npx tsc --noEmit || echo "No TypeScript config"
